/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project1.view;

import com.project1.model.Staff;
import com.project1.utility.view.Renderer;
import com.project1.view.dialog.LoginDialog;
import com.project1.view.dialog.RegisterDialog;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nguyenvanviet
 */
public class Main_FR extends javax.swing.JFrame {

    /**
     * Creates new form Main_FR
     */
    private Staff staff;
    private QLSP qlsp;
    private KhachHang khach_hang;
    private BanHang_fr ban_hang;
    private HashMap<JButton, JPanel> panels;
    private KhuyenMai khuyen_mai;
    private RegisterDialog nv;
    
    public Main_FR() {
        initComponents();
        
        var login = new LoginDialog(this, true);

        if (login.getStaff().isPresent()) {
            this.staff = login.getStaff().get();
        }
        
        qlsp = new QLSP();
        khach_hang = new KhachHang();
        khuyen_mai = new KhuyenMai();
        //nv = new RegisterDialog();
        ban_hang = new BanHang_fr(this.staff);
        panels = new HashMap<JButton, JPanel>() {{
            put (
                    product_manager
                    , new Renderer<>(qlsp.getPanel())
                            .getDefault(content_panel));
            put (
                    btn_customer
                    , new Renderer<>( khach_hang.getPanel())
                            .getDefault(content_panel));
            put (btn_payment
                    , new Renderer<>(ban_hang.getPanel())
                            .getDefault(content_panel));
            put (btn_KM 
                    , new Renderer<>(khuyen_mai.getPanel())
                            .getDefault(content_panel));
            
        }};
        
        for (var i: panels.entrySet()) {
            content_panel.add(i.getValue());
            i.getValue().setVisible(false);
        }
        
        
        reRender();
        this.setVisible(true);
    }
    
    public void reRender() {
        for (var i: panels.entrySet()) {
            i.getValue().setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        product_manager = new javax.swing.JButton();
        btn_customer = new javax.swing.JButton();
        btn_payment = new javax.swing.JButton();
        btn_KM = new javax.swing.JButton();
        btn_Nv = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        content_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        product_manager.setBackground(new java.awt.Color(255, 204, 204));
        product_manager.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        product_manager.setForeground(new java.awt.Color(153, 0, 51));
        product_manager.setText("QLSP");
        product_manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_managerActionPerformed(evt);
            }
        });

        btn_customer.setBackground(new java.awt.Color(255, 204, 204));
        btn_customer.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_customer.setForeground(new java.awt.Color(153, 0, 51));
        btn_customer.setText("khach hang");
        btn_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customerActionPerformed(evt);
            }
        });

        btn_payment.setBackground(new java.awt.Color(255, 204, 204));
        btn_payment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_payment.setForeground(new java.awt.Color(153, 0, 0));
        btn_payment.setText("ban hang");
        btn_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paymentActionPerformed(evt);
            }
        });

        btn_KM.setBackground(new java.awt.Color(255, 204, 204));
        btn_KM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_KM.setForeground(new java.awt.Color(153, 0, 51));
        btn_KM.setText("Khuyen Mai");
        btn_KM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KMActionPerformed(evt);
            }
        });

        btn_Nv.setBackground(new java.awt.Color(255, 204, 204));
        btn_Nv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_Nv.setForeground(new java.awt.Color(153, 0, 51));
        btn_Nv.setText("Nhân Vien");
        btn_Nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NvActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 204));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 51));
        jButton6.setText("Thoát");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(btn_Nv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_KM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_payment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_customer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(product_manager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btn_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(product_manager, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_KM, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Nv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout content_panelLayout = new javax.swing.GroupLayout(content_panel);
        content_panel.setLayout(content_panelLayout);
        content_panelLayout.setHorizontalGroup(
            content_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1051, Short.MAX_VALUE)
        );
        content_panelLayout.setVerticalGroup(
            content_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void product_managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_managerActionPerformed
        reRender();
        panels.get(product_manager).setVisible(true);
    }//GEN-LAST:event_product_managerActionPerformed

    private void btn_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customerActionPerformed
        reRender();
        panels.get(btn_customer).setVisible(true);
    }//GEN-LAST:event_btn_customerActionPerformed

    private void btn_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paymentActionPerformed
        reRender();
        ban_hang.reLoad();
        panels.get(btn_payment).setVisible(true);
    }//GEN-LAST:event_btn_paymentActionPerformed

    private void btn_KMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KMActionPerformed
        // TODO add your handling code here:
        reRender();
        panels.get(btn_KM).setVisible(true);
    }//GEN-LAST:event_btn_KMActionPerformed

    private void btn_NvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NvActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_KM;
    private javax.swing.JButton btn_Nv;
    private javax.swing.JButton btn_customer;
    private javax.swing.JButton btn_payment;
    private javax.swing.JPanel content_panel;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton product_manager;
    // End of variables declaration//GEN-END:variables
}
