/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project1.view;

import com.project1.model.Product;
import com.project1.model.ProductDetail;
import com.project1.model_adapter.ColorAdapter;
import com.project1.model_adapter.ProducerAdapter;
import com.project1.model_adapter.ProductDetailAdapter;
import com.project1.model_adapter.ProductLineAdapter;
import com.project1.repository.implement.ColorRepository;
import com.project1.repository.implement.ProductDetailReposytory;
import com.project1.repository.implement.ProductRepository;
import com.project1.service.implement.ColorService;
import com.project1.service.implement.ProducerService;
import com.project1.service.implement.ProductLineService;
import com.project1.view.dialog.ProducerDialog;
import com.project1.view.dialog.ProductColorForm;
import com.project1.view.dialog.ProductLineForm;
import com.project1.view.dialog.ProductSearchDialog;
import java.awt.Color;
import java.math.BigInteger;
import java.util.HashMap;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author nguyenvanviet
 */
public class QLSP extends javax.swing.JFrame {

    
    private ColorAdapter c_adapter;
    private ColorService c_service;
    private ColorRepository c_repo;
    
    private ProductRepository p_repo;
    
    private ProductLineAdapter pl_adapter;
    private ProductLineService pl_service;
    
    private ProducerAdapter pcr_adapter;
    private ProducerService pcr_service;
    /**
     * Creates new form QLSP
     */
    public QLSP() {
        initComponents();
        tbl_data.setAutoCreateRowSorter(true);
        c_adapter = new ColorAdapter();
        c_service = new ColorService();
        c_repo = new ColorRepository();
        
        p_repo = new ProductRepository();
        
        pl_adapter = new ProductLineAdapter();
        pl_service = new ProductLineService();
        
        pcr_adapter = new ProducerAdapter();
        pcr_service = new ProducerService();
        
        cbb_product_color.setModel(c_adapter.model());
        cbb_product_line.setModel(pl_adapter.model());
        cbb_producer.setModel(pcr_adapter.model());
        tbl_data.setModel(new ProductDetailAdapter().model());
    }
    
    public JPanel getPanel() {
        return content_panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        content_panel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        err_id = new javax.swing.JLabel();
        err_name = new javax.swing.JLabel();
        err_color = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        err_size = new javax.swing.JLabel();
        err_quantity = new javax.swing.JLabel();
        err_decryption = new javax.swing.JLabel();
        err_import_price = new javax.swing.JLabel();
        err_export_price = new javax.swing.JLabel();
        cbb_product_color = new javax.swing.JComboBox<>();
        cbb_product_line = new javax.swing.JComboBox<>();
        cbb_producer = new javax.swing.JComboBox<>();
        txt_product_id = new javax.swing.JTextField();
        txt_product_name = new javax.swing.JTextField();
        txt_product_size = new javax.swing.JTextField();
        txt_product_quantity = new javax.swing.JTextField();
        txt_product_decript = new javax.swing.JTextField();
        txt_product_import_price = new javax.swing.JTextField();
        txt_product_export_price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_insert = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Màu Sắc", "Dòng Sản Phẩm", "Nhà Sản Xuất", "Size", "Số Lượng", "Mô Tả", "Giá Nhập", "Giá Bán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);
        if (tbl_data.getColumnModel().getColumnCount() > 0) {
            tbl_data.getColumnModel().getColumn(0).setResizable(false);
            tbl_data.getColumnModel().getColumn(1).setResizable(false);
            tbl_data.getColumnModel().getColumn(2).setResizable(false);
            tbl_data.getColumnModel().getColumn(3).setResizable(false);
            tbl_data.getColumnModel().getColumn(4).setResizable(false);
            tbl_data.getColumnModel().getColumn(5).setResizable(false);
            tbl_data.getColumnModel().getColumn(6).setResizable(false);
            tbl_data.getColumnModel().getColumn(7).setResizable(false);
            tbl_data.getColumnModel().getColumn(8).setResizable(false);
            tbl_data.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        err_id.setBackground(new java.awt.Color(255, 255, 255));
        err_id.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        err_id.setText("Mã Sản Phẩm");

        err_name.setBackground(new java.awt.Color(255, 255, 255));
        err_name.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        err_name.setText("Tên Sản Phẩm");

        err_color.setBackground(new java.awt.Color(255, 255, 255));
        err_color.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        err_color.setText("Màu Sắc");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel5.setText("Dòng Sản Phẩm");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel6.setText("Nhà Sản Xuất");

        err_size.setBackground(new java.awt.Color(255, 255, 255));
        err_size.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        err_size.setText("kich co");

        err_quantity.setBackground(new java.awt.Color(255, 255, 255));
        err_quantity.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        err_quantity.setText("Số Lượng");

        err_decryption.setBackground(new java.awt.Color(255, 255, 255));
        err_decryption.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        err_decryption.setText("Mô Tả");

        err_import_price.setBackground(new java.awt.Color(255, 255, 255));
        err_import_price.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        err_import_price.setText("Giá Nhập");

        err_export_price.setBackground(new java.awt.Color(255, 255, 255));
        err_export_price.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        err_export_price.setText("Giá Bán");

        cbb_product_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_product_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_product_colorActionPerformed(evt);
            }
        });

        cbb_product_line.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_product_line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_product_lineActionPerformed(evt);
            }
        });

        cbb_producer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_producer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_producerActionPerformed(evt);
            }
        });

        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_insert.setText("Thêm");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        jButton5.setText("Sắp Xếp");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("clear form");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(err_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(err_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(err_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_insert)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbb_producer, 0, 258, Short.MAX_VALUE)
                            .addComponent(cbb_product_line, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_product_color, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_product_name)
                            .addComponent(txt_product_id))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(err_quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(err_decryption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(err_export_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(err_import_price)
                            .addComponent(err_size, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_product_import_price, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(txt_product_quantity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_product_decript, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_product_size, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_product_export_price)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(238, 238, 238)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(err_size, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_product_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_product_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_product_decript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_product_import_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(err_export_price, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_product_export_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(err_id)
                            .addComponent(txt_product_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(err_name)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(err_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(err_color)
                            .addComponent(cbb_product_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err_decryption, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbb_product_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err_import_price, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbb_producer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insert)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );

        jLabel2.setText("Thiết Lập Thông Tin Sản Phẩm");

        jButton4.setText("Tìm Kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout content_panelLayout = new javax.swing.GroupLayout(content_panel);
        content_panel.setLayout(content_panelLayout);
        content_panelLayout.setHorizontalGroup(
            content_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(content_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(content_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(content_panelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        content_panelLayout.setVerticalGroup(
            content_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(content_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        if (valid()) {
            new ProductDetailReposytory().insert(toProductDetail(new ProductDetail()));
            tbl_data.setModel(new ProductDetailAdapter().model());    
        }
    }//GEN-LAST:event_btn_insertActionPerformed

    public ProductDetail toProductDetail(ProductDetail product_deetail) {
        var pd = product_deetail;
        var c = c_repo.getByName(cbb_product_color.getSelectedItem().toString());
        var pcr = pcr_service.getByName(cbb_producer.getSelectedItem().toString());
        var pl = pl_service.getByName(cbb_product_line.getSelectedItem().toString());
        
        if (p_repo.findByIdProduct(txt_product_id.getText().trim())) {
            pd.setProduct(p_repo
                        .getByIdProduct(
                        txt_product_id.getText().trim())
                        .get(0));
        } else {
            var temp_product = new Product();
            temp_product.setIdProduct(txt_product_id.getText().trim());
            temp_product.setName(txt_product_name.getText().trim());
            p_repo.insert(temp_product);
            pd.setProduct(temp_product);
        }

        if (!c.isEmpty()) {
            pd.setColor(c.get(0));
        }
        if (!pcr.isEmpty()) {
            pd.setProducer(pcr.get(0));
        }
        if (!pl.isEmpty()) {
            pd.setProductLine(pl.get(0));
        }

        pd.setSize(Integer.valueOf(txt_product_size.getText()));
        pd.setQuantity(Integer.valueOf(txt_product_quantity.getText()));
        pd.setDecription(txt_product_decript.getText());
        pd.setImportPrice(new BigInteger(txt_product_import_price.getText()));
        pd.setExportPrice(new BigInteger(txt_product_export_price.getText()));
        return pd;
    }
    
    public boolean valid() {
        
        var err_map = new HashMap<JLabel, Boolean>() {{
            put (err_id,
                    Pattern.matches("^[a-zA-Z0-9]+[-]?[a-zA-Z0-9]$", txt_product_id.getText().trim()));
            put (err_name,
                    Pattern.matches("^[a-zA-Z0-9 ]+$", txt_product_name.getText().trim()));
            put (err_size,
                    Pattern.matches("^[1-9]([0-9]+)?$", txt_product_size.getText().trim()));
            put (err_quantity,
                    Pattern.matches("^[1-9]([0-9]+)?$", txt_product_quantity.getText().trim()));
            put (err_decryption,
                    Pattern.matches("^[a-zA-Z0-9 ]+$", txt_product_decript.getText().trim()));
            put (err_import_price,
                    Pattern.matches("^[1-9]([0-9]+)?$", txt_product_import_price.getText().trim()));
            put (err_export_price,
                    Pattern.matches("^[1-9]([0-9]+)?$", txt_product_export_price.getText().trim()));
        }};
        
        var result = true;
        
        for (var i: err_map.entrySet()) {
            if (!i.getValue()) {
                i.getKey().setForeground(Color.red);
                result = false;
            } else {
                i.getKey().setForeground(Color.white);
            }
        }
        
        return result;
        
    }
    
    public void clearForm() {
        txt_product_id.setText("");
        txt_product_name.setText("");
        cbb_product_color.setSelectedIndex(0);
        cbb_product_line.setSelectedIndex(0);
        cbb_producer.setSelectedIndex(0);
        txt_product_size.setText("");
        txt_product_quantity.setText("");
        txt_product_decript.setText("");
        txt_product_import_price.setText("");
        txt_product_export_price.setText("");
    }
    
    private void cbb_product_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_product_colorActionPerformed
        if (cbb_product_color.getSelectedItem().toString().compareTo("...") == 0) {
            var color = new ProductColorForm(this, true);
            color.setVisible(true);
            var value = color.getColor();
            if (value.isPresent()) {
                c_service.insert(value.get());
                cbb_product_color.setModel(c_adapter.model());
            }
        }
    }//GEN-LAST:event_cbb_product_colorActionPerformed

    private void cbb_producerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_producerActionPerformed
        
        if (cbb_producer.getSelectedItem().toString().compareTo("...") == 0) {
            var pcr = new ProducerDialog(this, true);
            pcr.setVisible(true);
            var value = pcr.getProducer();
            if (value.isPresent()) {
                if (pcr_service.insert(value.get()).isPresent()) {
                    System.out.println("added");
                } 
                cbb_producer.setModel(pcr_adapter.model());
            }
        }
    }//GEN-LAST:event_cbb_producerActionPerformed

    private void cbb_product_lineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_product_lineActionPerformed
        
        if (cbb_product_line.getSelectedItem().toString().compareTo("...") == 0) {
            var pl = new ProductLineForm(this, true);
            pl.setVisible(true);
            var value = pl.getProductLine();
            if (value.isPresent()) {
                if (pl_service.insert(value.get()).isPresent()) {
                    
                }cbb_product_line.setModel(pl_adapter.model());
            }
        }
    }//GEN-LAST:event_cbb_product_lineActionPerformed

    private void tbl_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        if (tbl_data.getSelectedRowCount() == 1) {
            var pd = new ProductDetailReposytory().getAll().get(tbl_data.getSelectedRow());
            txt_product_id.setText(pd.getProduct().getIdProduct());
            txt_product_name.setText(pd.getProduct().getName());
            cbb_product_color.setSelectedItem(pd.getColor());
            cbb_product_line.setSelectedItem(pd.getProductLine().getName());
            cbb_producer.setSelectedItem(pd.getProducer().getName());
            txt_product_size.setText(pd.getSize() + "");
            txt_product_quantity.setText(pd.getQuantity() + "");
            txt_product_decript.setText(pd.getDecription());
            txt_product_import_price.setText(pd.getImportPrice().toString());
            txt_product_export_price.setText(pd.getExportPrice().toString());
        }
        valid();
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tbl_data.getSelectedRowCount() == 1) {
            if (valid()) {
                var repo = new ProductDetailReposytory();
                repo.update(toProductDetail(repo.getAll().get(tbl_data.getSelectedRow())));
                tbl_data.setModel(new ProductDetailAdapter().model());                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clearForm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        var pds = new ProductSearchDialog(this, true);
        pds.setVisible(true);
        tbl_data.setModel(new ProductDetailAdapter().searchModel(pds.getSearchREsult()));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_insert;
    private javax.swing.JComboBox<String> cbb_producer;
    private javax.swing.JComboBox<String> cbb_product_color;
    private javax.swing.JComboBox<String> cbb_product_line;
    private javax.swing.JPanel content_panel;
    private javax.swing.JLabel err_color;
    private javax.swing.JLabel err_decryption;
    private javax.swing.JLabel err_export_price;
    private javax.swing.JLabel err_id;
    private javax.swing.JLabel err_import_price;
    private javax.swing.JLabel err_name;
    private javax.swing.JLabel err_quantity;
    private javax.swing.JLabel err_size;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txt_product_decript;
    private javax.swing.JTextField txt_product_export_price;
    private javax.swing.JTextField txt_product_id;
    private javax.swing.JTextField txt_product_import_price;
    private javax.swing.JTextField txt_product_name;
    private javax.swing.JTextField txt_product_quantity;
    private javax.swing.JTextField txt_product_size;
    // End of variables declaration//GEN-END:variables
}
