/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.project1.view.dialog;

import com.project1.model.Producer;
import com.project1.model_adapter.ProducerAdapter;
import com.project1.service.implement.ProducerService;
import java.awt.Color;
import java.util.HashMap;
import java.util.Optional;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author thinhorigami-rio
 */
public class ProducerDialog extends javax.swing.JDialog {

    private Producer p;
    /**
     * Creates new form ProducerForm
     */
    public ProducerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refresh();
    }

    public Optional<Producer> getProducer() {
        if (valid()) {
            var pcr = new Producer();
            pcr.setIdProducer(txt_producer_id.getText().trim());
            pcr.setName(txt_producer_name.getText().trim());
            return Optional.of(pcr);
        }
        return Optional.empty();
    }

    public boolean valid() {

        var err_map = new HashMap<JLabel, Boolean>() {
            {
                put(err_producer_id, Pattern.matches(
                        "^[a-zA-Z0-9]+[-]?[a-zA-Z0-9]+$",
                         txt_producer_id.getText().trim()));
                put(err_producer_name, Pattern.matches(
                        "^[a-zA-Z ]+$",
                         txt_producer_name.getText().trim()));
            }
        };

        boolean result = true;
        for (var i : err_map.entrySet()) {
            if (!i.getValue()) {
                i.getKey().setVisible(true);
                result = false;
            } else {
                i.getKey().setVisible(false);
            }
        }
        return result;
    }
    
    public void refresh() {
        tbl_data.setModel(new ProducerAdapter().tableModel());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_producer_name = new javax.swing.JTextField();
        txt_producer_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        err_producer_id = new javax.swing.JLabel();
        err_producer_name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ma nha san xuat");

        jLabel2.setText("ten ma san xuat");

        txt_producer_id.setToolTipText("hehe");

        jButton1.setText("them");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        err_producer_id.setText("! ma nha san xuat chi duoc chua cac ki tu [a-z,A-Z,0-9]");

        err_producer_name.setText("! ten nha san xuat chi duoc chua cac ki ti [a-z,A-Z]");

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        jButton2.setText("sua");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(err_producer_id)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_producer_id)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(err_producer_name)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_producer_name))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(err_producer_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_producer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(err_producer_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_producer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (valid()) {
            var value = new Producer();
            value.setIdProducer(txt_producer_id.getText().trim());
            value.setName(txt_producer_name.getText().trim());
            if (new ProducerService().insert(value).isPresent()) {
                JOptionPane.showMessageDialog(this, "them thanh cong");
            } else 
                JOptionPane.showMessageDialog(this, "them that bai");
            refresh();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        if (tbl_data.getSelectedRowCount() == 1) {
            this.p = new ProducerService().getAll().get(tbl_data.getSelectedRow());
            txt_producer_id.setText(p.getIdProducer());
            txt_producer_name.setText(p.getName());
        }
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        p.setIdProducer(txt_producer_id.getText().trim());
        p.setName(txt_producer_name.getText().trim());
        
        if (new ProducerService().update(p).isPresent()) {
            JOptionPane.showMessageDialog(this, "sua thanh cong");
            refresh();
        } else JOptionPane.showMessageDialog(this, "sua that bai");
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel err_producer_id;
    private javax.swing.JLabel err_producer_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txt_producer_id;
    private javax.swing.JTextField txt_producer_name;
    // End of variables declaration//GEN-END:variables
}
