/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.project1.view.dialog;

import com.project1.model.Color;
import com.project1.model.ProductLine;
import com.project1.model_adapter.ProductLineAdapter;
import com.project1.service.implement.ColorService;
import com.project1.service.implement.ProductLineService;
import java.util.HashMap;
import java.util.Optional;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author thinhorigami-rio
 */
public class ProductLineForm extends javax.swing.JDialog {

    public Optional<ProductLine> product_line;
    /**
     * Creates new form ProductLineForm
     */
    public ProductLineForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refresh();
    }
    
    
    public Optional<ProductLine> getProductLine() {
        if (valid()) {
            var pl = new ProductLine();
            pl.setIdProductLine(txt_id.getText().trim());
            pl.setName(txt_name.getText().trim());
            return Optional.of(pl);
        }
        return Optional.empty();
    }
    
    public void refresh() {
        tbl_data.setModel(new ProductLineAdapter().tableModel());
    }
    
    public boolean valid() {

        var err_map = new HashMap<JLabel, Boolean>() {{
                put(err_product_line_id, Pattern.matches(
                        "^[a-zA-Z0-9]+[-]?[a-zA-Z0-9]+$",
                         txt_id.getText().trim()));
                put(err_product_line_name, Pattern.matches("^[a-zA-Z ]+$",
                         txt_name.getText().trim()));
        }};

        boolean result = true;
        for (var i : err_map.entrySet()) {
            if (!i.getValue()) {
                i.getKey().setVisible(true);
                System.out.println("error");
                result = false;
            } else {
                i.getKey().setVisible(false);
            }
        }
        return result;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        err_product_line_name = new javax.swing.JLabel();
        err_product_line_id = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        sua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ten dong san pham");

        jLabel2.setText("ma dong san pham");

        err_product_line_name.setText("ten dong san pham chi duoc chua cac ki to [a-z,A-Z,0-9]");

        err_product_line_id.setText("ma dong san pham chi chua cac ki tu [a-z,A-Z,0-9]");

        jButton1.setText("them");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        sua.setText("sua");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_name)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(err_product_line_name)
                                        .addGap(0, 112, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(err_product_line_id)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txt_id)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(sua)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(err_product_line_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(err_product_line_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(sua))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (valid()) {
            var c = new ProductLine();
            c.setIdProductLine(txt_id.getText().trim());
            c.setName(txt_name.getText().trim());
            if (new ProductLineService().insert(c).isPresent()) {
                this.product_line = Optional.of(c);
                refresh();
                JOptionPane.showMessageDialog(this, "them thanh cong");
            } else JOptionPane.showMessageDialog(this, "them that bai");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        if (tbl_data.getSelectedRowCount() == 1) {
            this.product_line = Optional.of(new ProductLineService()
                    .getAll()
                    .get(tbl_data.getSelectedRow())
            );
            txt_id.setText(this.product_line.get().getIdProductLine());
            txt_name.setText(this.product_line.get().getName());
        }
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        if (new ProductLineService().update(this.product_line.get()).isPresent()) {
            refresh();
            JOptionPane.showMessageDialog(this, "sua thanh xong");
        } else 
            JOptionPane.showMessageDialog(this, "sua that bai");
    }//GEN-LAST:event_suaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel err_product_line_id;
    private javax.swing.JLabel err_product_line_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sua;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
